name: Tastingflight
options:
  bundleIdPrefix: com.shimondeitel.whiskeylog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Tastingflight:
    type: application
    platform: iOS
    sources:
      - path: Tastingflight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.whiskeylog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Tastingflight/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  TastingflightTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TastingflightTests
      - path: Tastingflight.storekit
    dependencies:
      - target: Tastingflight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.whiskeylog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  TastingflightUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TastingflightUITests
    dependencies:
      - target: Tastingflight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.whiskeylog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Tastingflight:
    build:
      targets:
        Tastingflight: all
        TastingflightTests: [test]
        TastingflightUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Tastingflight.storekit
    test:
      config: Debug
      storeKitConfiguration: Tastingflight.storekit
      targets:
        - TastingflightTests
        - TastingflightUITests
    archive:
      config: Release
